export const categories = [
  {
    id: 1,
    slug: "fresh-vegetables",
    name: "Fresh Vegetables",
    shortName: "Vegetables",
    description: "Leafy picks, roots, and farm-cut essentials delivered chilled and crisp.",
    itemCount: 142,
    deliveryTime: "9 mins",
    tint: "#E7F8D8",
  },
  {
    id: 2,
    slug: "seasonal-fruits",
    name: "Seasonal Fruits",
    shortName: "Fruits",
    description: "Handpicked, naturally sweet fruit boxes for breakfast bowls and snack breaks.",
    itemCount: 98,
    deliveryTime: "11 mins",
    tint: "#FFF0D2",
  },
  {
    id: 3,
    slug: "dairy-breakfast",
    name: "Dairy & Breakfast",
    shortName: "Dairy",
    description: "Milk, yogurt, butter, and ready breakfast staples for every morning rush.",
    itemCount: 76,
    deliveryTime: "13 mins",
    tint: "#E7F1FF",
  },
  {
    id: 4,
    slug: "snacks-drinks",
    name: "Snacks & Drinks",
    shortName: "Snacks",
    description: "Crunchy, fizzy, and comforting pantry favorites for work and movie nights.",
    itemCount: 163,
    deliveryTime: "12 mins",
    tint: "#FFF0E8",
  },
  {
    id: 5,
    slug: "bakery-desserts",
    name: "Bakery & Desserts",
    shortName: "Bakery",
    description: "Warm breads, artisanal buns, and sweet celebratory bites.",
    itemCount: 61,
    deliveryTime: "15 mins",
    tint: "#FBEDE2",
  },
  {
    id: 6,
    slug: "household-care",
    name: "Household Care",
    shortName: "Home Care",
    description: "Daily cleaning essentials with easy bulk packs and curated combos.",
    itemCount: 84,
    deliveryTime: "18 mins",
    tint: "#EAF6F7",
  },
];

export const heroSlides = [
  {
    id: 1,
    eyebrow: "Fresh arrival",
    title: "Morning market quality, at your door before the kettle boils.",
    description: "Curated fruit and veggie baskets, bakery staples, and breakfast picks with premium packaging and express delivery.",
    cta: "Shop groceries",
    secondaryCta: "See offers",
    image: "/images/hero/market-fresh.svg",
    accent: "#E8F7D8",
    badge: "Up to 35% off on fresh picks",
  },
  {
    id: 2,
    eyebrow: "Weekend host mode",
    title: "Build snack boards, dessert trays, and pantry refills in a single tap.",
    description: "From sparkling drinks to bakery boxes, design-forward grocery shopping with Blinkit speed and Flipkart-style breadth.",
    cta: "Browse categories",
    secondaryCta: "Trending products",
    image: "/images/hero/snack-party.svg",
    accent: "#FFF2D9",
    badge: "Party bundles from \u20B919",
  },
  {
    id: 3,
    eyebrow: "Wellness staples",
    title: "Organic greens, probiotic dairy, and mindful pantry upgrades that feel premium.",
    description: "Smart curation, clear pricing, and elegant browsing for customers who want faster checkouts without losing taste.",
    cta: "Explore wellness",
    secondaryCta: "New arrivals",
    image: "/images/hero/wellness-crate.svg",
    accent: "#E6F3FF",
    badge: "Free delivery above \u20B925",
  },
];

export const featureHighlights = [
  {
    title: "10-minute promise",
    description: "Express slots backed by live inventory and rider batching.",
  },
  {
    title: "Curated freshness",
    description: "Premium fruits and vegetables sourced from trusted farm partners.",
  },
  {
    title: "Daily savings",
    description: "Combo packs, smart offers, and cart-level coupons across essentials.",
  },
  {
    title: "One-tap reorder",
    description: "Fast repeat shopping for milk runs, staples, and weekly refills.",
  },
];

export const products = [
  {
    id: 101,
    slug: "farm-fresh-spinach-bundle",
    name: "Farm Fresh Spinach Bundle",
    category: "fresh-vegetables",
    unit: "250 g",
    price: 3.2,
    originalPrice: 4.1,
    rating: 4.8,
    reviews: 148,
    deliveryTime: "9 mins",
    badge: "Fresh cut",
    image: "/images/products/produce-crate.svg",
    tint: "#E7F8D8",
    description: "Tender, iron-rich spinach leaves washed, trimmed, and packed for smoothies, curries, and quick saute bowls.",
    highlights: ["Farm sourced", "Washed pack", "High in iron"],
  },
  {
    id: 102,
    slug: "vine-ripened-tomato-box",
    name: "Vine Ripened Tomato Box",
    category: "fresh-vegetables",
    unit: "500 g",
    price: 4.5,
    originalPrice: 5.6,
    rating: 4.7,
    reviews: 96,
    deliveryTime: "10 mins",
    badge: "Chef pick",
    image: "/images/products/produce-crate.svg",
    tint: "#FEE7D9",
    description: "Juicy tomatoes selected for balanced sweetness, ideal for salads, sauces, and breakfast toasts.",
    highlights: ["Hand sorted", "Salad ready", "Kitchen staple"],
  },
  {
    id: 103,
    slug: "mango-sunrise-selection",
    name: "Mango Sunrise Selection",
    category: "seasonal-fruits",
    unit: "4 pcs",
    price: 8.9,
    originalPrice: 10.2,
    rating: 4.9,
    reviews: 233,
    deliveryTime: "11 mins",
    badge: "Season special",
    image: "/images/products/fruit-basket.svg",
    tint: "#FFF0D2",
    description: "Aromatic seasonal mangoes with rich flesh and low fiber, packed in a soft-cushion gift tray.",
    highlights: ["Naturally sweet", "Seasonal favorite", "Gift-worthy pack"],
  },
  {
    id: 104,
    slug: "citrus-boost-bag",
    name: "Citrus Boost Bag",
    category: "seasonal-fruits",
    unit: "1 kg",
    price: 6.8,
    originalPrice: 8,
    rating: 4.6,
    reviews: 74,
    deliveryTime: "12 mins",
    badge: "Vitamin C",
    image: "/images/products/fruit-basket.svg",
    tint: "#FFECC8",
    description: "A bright mix of oranges and sweet lime for juices, hydration, and daily wellness routines.",
    highlights: ["Juice friendly", "Hydrating", "Family pack"],
  },
  {
    id: 105,
    slug: "artisan-yogurt-protein-pack",
    name: "Artisan Yogurt Protein Pack",
    category: "dairy-breakfast",
    unit: "400 g",
    price: 5.9,
    originalPrice: 6.7,
    rating: 4.8,
    reviews: 115,
    deliveryTime: "13 mins",
    badge: "Breakfast best",
    image: "/images/products/dairy-box.svg",
    tint: "#E6F1FF",
    description: "Creamy probiotic yogurt with a smooth finish, perfect for parfait bowls and late-night desserts.",
    highlights: ["High protein", "Probiotic culture", "Smooth texture"],
  },
  {
    id: 106,
    slug: "golden-butter-croissant-set",
    name: "Golden Butter Croissant Set",
    category: "bakery-desserts",
    unit: "Pack of 4",
    price: 7.4,
    originalPrice: 8.5,
    rating: 4.7,
    reviews: 89,
    deliveryTime: "14 mins",
    badge: "Baked today",
    image: "/images/products/bakery-bag.svg",
    tint: "#FBEDE2",
    description: "Flaky layered croissants made with cultured butter and packed warm in bakery paper sleeves.",
    highlights: ["Butter rich", "Layered texture", "Cafe style"],
  },
  {
    id: 107,
    slug: "sparkling-berry-drink-pack",
    name: "Sparkling Berry Drink Pack",
    category: "snacks-drinks",
    unit: "6 x 250 ml",
    price: 9.3,
    originalPrice: 11,
    rating: 4.5,
    reviews: 61,
    deliveryTime: "12 mins",
    badge: "Party ready",
    image: "/images/products/snack-box.svg",
    tint: "#FFE7F0",
    description: "Light sparkling berry beverage set for hosting trays, work breaks, and weekend picnics.",
    highlights: ["Low fizz burn", "Chilled pack", "Shareable size"],
  },
  {
    id: 108,
    slug: "sea-salt-chip-variety-box",
    name: "Sea Salt Chip Variety Box",
    category: "snacks-drinks",
    unit: "8 packs",
    price: 10.5,
    originalPrice: 12.4,
    rating: 4.6,
    reviews: 104,
    deliveryTime: "12 mins",
    badge: "Top snack",
    image: "/images/products/snack-box.svg",
    tint: "#FFF0E8",
    description: "Small-batch kettle chips in balanced savory flavors packed for desk drawers and movie marathons.",
    highlights: ["Crunchy batch", "Shareable box", "Travel friendly"],
  },
  {
    id: 109,
    slug: "daily-milk-family-pack",
    name: "Daily Milk Family Pack",
    category: "dairy-breakfast",
    unit: "2 L",
    price: 4.2,
    originalPrice: 4.9,
    rating: 4.8,
    reviews: 203,
    deliveryTime: "10 mins",
    badge: "Best seller",
    image: "/images/products/dairy-box.svg",
    tint: "#E8F4FF",
    description: "Chilled milk with secure seal packaging for tea, breakfast cereal, and everyday cooking needs.",
    highlights: ["Daily essential", "Cold chain packed", "Secure seal"],
  },
  {
    id: 110,
    slug: "clean-home-starter-bundle",
    name: "Clean Home Starter Bundle",
    category: "household-care",
    unit: "3 items",
    price: 12.8,
    originalPrice: 15.2,
    rating: 4.4,
    reviews: 57,
    deliveryTime: "18 mins",
    badge: "Value combo",
    image: "/images/products/home-care.svg",
    tint: "#EAF6F7",
    description: "Surface spray, sponge wipes, and dish gel curated as an easy refill combo for busy homes.",
    highlights: ["Bundle value", "Everyday care", "Quick refill"],
  },
  {
    id: 111,
    slug: "avocado-toast-breakfast-kit",
    name: "Avocado Toast Breakfast Kit",
    category: "dairy-breakfast",
    unit: "Combo",
    price: 11.7,
    originalPrice: 13.1,
    rating: 4.8,
    reviews: 78,
    deliveryTime: "14 mins",
    badge: "Brunch box",
    image: "/images/products/bakery-bag.svg",
    tint: "#EEF5D7",
    description: "Avocados, seeded bread, and creamy spread bundled into a stylish brunch-ready combo.",
    highlights: ["Curated combo", "Cafe style", "Quick brunch"],
  },
  {
    id: 112,
    slug: "berry-cheesecake-cups",
    name: "Berry Cheesecake Cups",
    category: "bakery-desserts",
    unit: "2 cups",
    price: 6.3,
    originalPrice: 7.2,
    rating: 4.9,
    reviews: 92,
    deliveryTime: "15 mins",
    badge: "Dessert drop",
    image: "/images/products/bakery-bag.svg",
    tint: "#FFEAF3",
    description: "Layered cream cheese dessert cups finished with berry compote for a polished after-dinner treat.",
    highlights: ["Creamy finish", "Portion perfect", "Celebration ready"],
  },
];

export const cartItems = [
  {
    id: 1,
    productSlug: "farm-fresh-spinach-bundle",
    quantity: 2,
  },
  {
    id: 2,
    productSlug: "artisan-yogurt-protein-pack",
    quantity: 1,
  },
  {
    id: 3,
    productSlug: "golden-butter-croissant-set",
    quantity: 1,
  },
];

export const deliverySlots = [
  "Deliver in 10-15 mins",
  "Schedule for 7:00 PM - 8:00 PM",
  "Schedule for tomorrow morning",
];

export const paymentMethods = [
  "Pay on delivery",
  "UPI / Wallet",
  "Credit / Debit card",
  "Mock PayPal checkout",
];

export const aboutStats = [
  { label: "Dark stores", value: "35+" },
  { label: "Fresh SKUs", value: "4.8k" },
  { label: "Cities served", value: "12" },
  { label: "Repeat shoppers", value: "89%" },
];

export const contactCards = [
  {
    title: "Customer care",
    value: "+1 (800) 555-0142",
    detail: "7 AM to 11 PM for order help, refunds, and delivery updates.",
  },
  {
    title: "Vendor partnerships",
    value: "partners@freshcart.studio",
    detail: "For farm sourcing, artisanal brands, and retail collaborations.",
  },
  {
    title: "Corporate office",
    value: "14 Market Lane, Bengaluru",
    detail: "Design-led operations, category planning, and logistics strategy hub.",
  },
];

export const footerSections = [
  {
    title: "Shop",
    links: [
      { label: "Fresh produce", href: "/categories/fresh-produce" },
      { label: "Fresh fruits", href: "/categories/fresh-fruits" },
      { label: "Dairy & breakfast", href: "/categories/dairy-breakfast" },
      { label: "Snacks & beverages", href: "/categories/snacks-beverages" },
    ],
  },
  {
    title: "Company",
    links: [
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
      { label: "Delivery promise", href: "/products" },
      { label: "Cart", href: "/cart" },
    ],
  },
];

export const getCategoryBySlug = (slug) => categories.find((category) => category.slug === slug);

export const getProductBySlug = (slug) => products.find((product) => product.slug === slug);

export const getProductsByCategory = (slug) => products.filter((product) => product.category === slug);

export const getTrendingProducts = () => products.slice(0, 8);



